//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionEscritorio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chat", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio")]
    [System.SerializableAttribute()]
    public partial class Chat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServiceReference1.Cliente pObjClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionEscritorio.ServiceReference1.Empleado pObjEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChat {
            get {
                return this.IdChatField;
            }
            set {
                if ((this.IdChatField.Equals(value) != true)) {
                    this.IdChatField = value;
                    this.RaisePropertyChanged("IdChat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServiceReference1.Cliente pObjCliente {
            get {
                return this.pObjClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.pObjClienteField, value) != true)) {
                    this.pObjClienteField = value;
                    this.RaisePropertyChanged("pObjCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionEscritorio.ServiceReference1.Empleado pObjEmpleado {
            get {
                return this.pObjEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.pObjEmpleadoField, value) != true)) {
                    this.pObjEmpleadoField = value;
                    this.RaisePropertyChanged("pObjEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCliente {
            get {
                return this.EmailClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailClienteField, value) != true)) {
                    this.EmailClienteField = value;
                    this.RaisePropertyChanged("EmailCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente {
            get {
                return this.NombreClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreClienteField, value) != true)) {
                    this.NombreClienteField = value;
                    this.RaisePropertyChanged("NombreCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio")]
    [System.SerializableAttribute()]
    public partial class Empleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoEmpleado {
            get {
                return this.EstadoEmpleadoField;
            }
            set {
                if ((this.EstadoEmpleadoField.Equals(value) != true)) {
                    this.EstadoEmpleadoField = value;
                    this.RaisePropertyChanged("EstadoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpleado {
            get {
                return this.NombreEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpleadoField, value) != true)) {
                    this.NombreEmpleadoField = value;
                    this.RaisePropertyChanged("NombreEmpleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebChat")]
    public interface IWebChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearChat", ReplyAction="http://tempuri.org/IWebChat/CrearChatResponse")]
        int CrearChat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearChat", ReplyAction="http://tempuri.org/IWebChat/CrearChatResponse")]
        System.Threading.Tasks.Task<int> CrearChatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearMensaje", ReplyAction="http://tempuri.org/IWebChat/CrearMensajeResponse")]
        void CrearMensaje(int pIdChat, int pIdUsuario, string pTextoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/CrearMensaje", ReplyAction="http://tempuri.org/IWebChat/CrearMensajeResponse")]
        System.Threading.Tasks.Task CrearMensajeAsync(int pIdChat, int pIdUsuario, string pTextoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerChat", ReplyAction="http://tempuri.org/IWebChat/ObtenerChatResponse")]
        AplicacionEscritorio.ServiceReference1.Chat ObtenerChat(int pIdChat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebChat/ObtenerChat", ReplyAction="http://tempuri.org/IWebChat/ObtenerChatResponse")]
        System.Threading.Tasks.Task<AplicacionEscritorio.ServiceReference1.Chat> ObtenerChatAsync(int pIdChat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebChatChannel : AplicacionEscritorio.ServiceReference1.IWebChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebChatClient : System.ServiceModel.ClientBase<AplicacionEscritorio.ServiceReference1.IWebChat>, AplicacionEscritorio.ServiceReference1.IWebChat {
        
        public WebChatClient() {
        }
        
        public WebChatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebChatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebChatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebChatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearChat() {
            return base.Channel.CrearChat();
        }
        
        public System.Threading.Tasks.Task<int> CrearChatAsync() {
            return base.Channel.CrearChatAsync();
        }
        
        public void CrearMensaje(int pIdChat, int pIdUsuario, string pTextoMensaje) {
            base.Channel.CrearMensaje(pIdChat, pIdUsuario, pTextoMensaje);
        }
        
        public System.Threading.Tasks.Task CrearMensajeAsync(int pIdChat, int pIdUsuario, string pTextoMensaje) {
            return base.Channel.CrearMensajeAsync(pIdChat, pIdUsuario, pTextoMensaje);
        }
        
        public AplicacionEscritorio.ServiceReference1.Chat ObtenerChat(int pIdChat) {
            return base.Channel.ObtenerChat(pIdChat);
        }
        
        public System.Threading.Tasks.Task<AplicacionEscritorio.ServiceReference1.Chat> ObtenerChatAsync(int pIdChat) {
            return base.Channel.ObtenerChatAsync(pIdChat);
        }
    }
}
